# Generated by Django 6.0.5 on 2026-06-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
