# Generated by Django 6.0.5 on 2026-06-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_gin_search_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalqueue',
            name='object_type',
            field=models.CharField(choices=[('topic', 'Topic'), ('category', 'Category'), ('subcategory', 'SubCategory'), ('pdf_upload', 'PDF Upload'), ('question', 'Question'), ('answer', 'Answer')], max_length=50),
        ),
    ]
