# Generated by Django 6.0.5 on 2026-06-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfupload',
            name='processed',
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='process_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
